# Generated by Django 5.2.6 on 2025-11-22 07:52

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    categories = [
        {'name': 'GRANITE'},
        {'name': 'MARBLE'},
        {'name': 'QUARTZ'},
    ]
    for category_data in categories:
        category_data['slug'] = slugify(category_data['name'])
        Category.objects.create(**category_data)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(create_initial_categories),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 10x10ft', max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
    ]
