# Generated by Django 5.2.6 on 2025-11-23 12:00

from django.db import migrations
from django.utils.text import slugify

def create_additional_categories(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    categories = [
        {'name': 'CARRARA'},
        {'name': 'CALACATTA'},
        {'name': 'STATUARIO'},
        {'name': 'EMPERADOR'},
        {'name': 'CREMA MARFIL'},
    ]
    for category_data in categories:
        category_data['slug'] = slugify(category_data['name'])
        Category.objects.create(**category_data)

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.RunPython(create_additional_categories),
    ]
