# Generated by Django 4.2.27 on 2026-01-22 10:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='The main content of the blog post.', verbose_name='Content'),
        ),
    ]
