# Generated by Django 5.2.6 on 2026-01-30 12:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_wishlist_unique_together_wishlist_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='The main content of the blog post.', verbose_name='Content'),
        ),
    ]
